resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false


- bash: |
   # Write your commands here
   cat > .env << EOF
   PRODUCT_SERVICE_BASE_URL=https://abeltailwindproductservice.azurewebsites.net
   INVENTORY_SERVICE_BASE_URL=https://abelinventoryserviceapi.azurewebsites.net
   EOF
   # Use the environment variables input below to pass secret variables to this script
  displayName: 'Set up DB Connection'

- bash: |
   # Write your commands here
   npm run build
   ls
   # Use the environment variables input below to pass secret variables to this script
  displayName: 'Build App'

- task: ArchiveFiles@2
  displayName: 'Archive dist'
  inputs:
    rootFolderOrFile: dist

    includeRootFolder: false


- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '**/*.zip'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'


